#!/usr/bin/env bash
#
# One-shot installer for the TrashPanda backend on a fresh VPS.
#
# Run as root on RackNerd (Debian/Ubuntu) once. Idempotent — safe to
# re-run. Sets up:
#
#   * /root/trashpanda                     (git checkout)
#   * /root/trashpanda/.venv               (python virtualenv)
#   * /etc/trashpanda/backend.env          (operator token + env vars)
#   * /etc/systemd/system/trashpanda-backend.service
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/.../deploy/install_vps.sh | bash
#   # or, after cloning manually:
#   bash deploy/install_vps.sh
#
# Re-run after a code change: deploy/update_vps.sh

set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/AlexanderAtlasLuthor/TrashPanda}"
REPO_BRANCH="${REPO_BRANCH:-main}"
REPO_DIR="${REPO_DIR:-/root/trashpanda}"
SERVICE_NAME="trashpanda-backend"
ENV_DIR="/etc/trashpanda"
ENV_FILE="${ENV_DIR}/backend.env"

log() { printf '\033[1;32m[deploy]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[deploy]\033[0m %s\n' "$*" >&2; }

if [[ "${EUID}" -ne 0 ]]; then
    warn "must be run as root"
    exit 1
fi

# ---- 1. System dependencies ---------------------------------------------- #
log "installing system packages"
apt-get update -y
apt-get install -y \
    git python3 python3-venv python3-pip ca-certificates curl

# ---- 2. Repository checkout ---------------------------------------------- #
if [[ -d "${REPO_DIR}/.git" ]]; then
    log "repo already at ${REPO_DIR}; fetching latest ${REPO_BRANCH}"
    git -C "${REPO_DIR}" fetch --depth=1 origin "${REPO_BRANCH}"
    git -C "${REPO_DIR}" checkout "${REPO_BRANCH}"
    git -C "${REPO_DIR}" reset --hard "origin/${REPO_BRANCH}"
else
    log "cloning ${REPO_URL} into ${REPO_DIR}"
    git clone --depth=1 --branch "${REPO_BRANCH}" "${REPO_URL}" "${REPO_DIR}"
fi

# ---- 3. Python virtualenv + deps ---------------------------------------- #
if [[ ! -x "${REPO_DIR}/.venv/bin/python" ]]; then
    log "creating python virtualenv"
    python3 -m venv "${REPO_DIR}/.venv"
fi
log "installing python dependencies"
"${REPO_DIR}/.venv/bin/pip" install --upgrade pip wheel >/dev/null
"${REPO_DIR}/.venv/bin/pip" install -r "${REPO_DIR}/requirements.txt"
"${REPO_DIR}/.venv/bin/pip" install uvicorn

# ---- 4. Runtime directories --------------------------------------------- #
mkdir -p "${REPO_DIR}/runtime" "${REPO_DIR}/.cache"

# ---- 5. Environment file (operator token, etc.) ------------------------- #
mkdir -p "${ENV_DIR}"
chmod 750 "${ENV_DIR}"
if [[ ! -f "${ENV_FILE}" ]]; then
    log "generating ${ENV_FILE} with a fresh operator token"
    TOKEN="$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
    cat > "${ENV_FILE}" <<EOF
# Auto-generated by deploy/install_vps.sh on $(date -Iseconds)
# Edit values here and run: systemctl restart ${SERVICE_NAME}

# Bearer token enforced on every /api/operator/* request.
# Rotate by appending the new token to TRASHPANDA_OPERATOR_TOKENS,
# rolling out the operator UI, and then replacing TRASHPANDA_OPERATOR_TOKEN.
TRASHPANDA_OPERATOR_TOKEN=${TOKEN}
# TRASHPANDA_OPERATOR_TOKENS=

# Wall-clock ceiling per job (seconds). 0 disables.
TRASHPANDA_MAX_JOB_SECONDS=2700

# UI label surfaced via /system/info.
TRASHPANDA_DEPLOYMENT=vps
TRASHPANDA_BACKEND_LABEL=racknerd
EOF
    chmod 640 "${ENV_FILE}"
    log "operator token written to ${ENV_FILE}"
    log "  copy this token into trashpanda-next/.env.local on your laptop:"
    printf '    TRASHPANDA_OPERATOR_TOKEN=%s\n' "${TOKEN}"
else
    log "${ENV_FILE} already exists — leaving operator token unchanged"
fi

# ---- 6. systemd unit ---------------------------------------------------- #
log "installing systemd unit"
install -m 0644 \
    "${REPO_DIR}/deploy/trashpanda-backend.service" \
    "/etc/systemd/system/${SERVICE_NAME}.service"
systemctl daemon-reload
systemctl enable "${SERVICE_NAME}"
systemctl restart "${SERVICE_NAME}"

# ---- 7. Smoke check ----------------------------------------------------- #
log "waiting for /healthz to come up"
for i in 1 2 3 4 5 6 7 8 9 10; do
    if curl -fsS "http://127.0.0.1:8000/healthz" >/dev/null 2>&1; then
        log "backend healthy"
        curl -s "http://127.0.0.1:8000/healthz" | python3 -m json.tool || true
        break
    fi
    sleep 1
    if [[ "${i}" == "10" ]]; then
        warn "/healthz did not respond after 10s — see: journalctl -u ${SERVICE_NAME} -n 100"
        exit 1
    fi
done

log "done. backend is running on 127.0.0.1:8000."
log "open the SSH tunnel from your laptop:"
log "  ssh -N -L 8001:127.0.0.1:8000 root@<vps_ip>"
